# Generated by Django 4.0.6 on 2022-07-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='author',
            new_name='user',
        ),
    ]
