# Generated by Django 4.0.6 on 2022-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0003_author_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='short_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='links',
            field=models.TextField(blank=True),
        ),
    ]
