# Generated by Django 4.0.6 on 2022-07-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0004_author_short_url_author_url_alter_author_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='url',
        ),
    ]
