# Generated by Django 4.0.6 on 2022-07-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0007_alter_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author',
        ),
    ]
